export const CounterTwoActionTypes = {
  INCREMENT_TWO: "INCREMENT_TWO",
  DECREMENT_TWO: "DECREMENT_TWO",
  RESET_TWO: "RESET_TWO",
  SECOND_INCREMENT_TWO: "SECOND_INCREMENT_TWO",
  SECOND_DECREMENT_TWO: "SECOND_DECREMENT_TWO",
  SECOND_RESET_TWO: "SECOND_RESET_TWO",
  STORE_INPUT_VALUE: "STORE_INPUT_VALUE"
};
